name: 'dataosphere'
version: '1.0.0'
profile: 'dataosphere'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

snapshots:
  dataosphere:          
    +schema: snapshots  
    +tags: ['snapshot', 'wash', 'kobo']

models:
  dataosphere:
    staging:
      +materialized: view
      +tags: ["wash"]
      +schema: stage




    


